Entrega 1: SOLID
elagarrigue/AyDS22-AK-Lisboa2 pull request #1
Opened 2022-04-13 14:11 UTC by brancomartinezc

Cambios en la visualización de las fechas de las canciones, respetando los principios SOLID.

2022-04-14 22:08 UTC, elagarrigue requested changes
Muy bien en general, tienen que resolver el tipo de dato date precision y otros comentarios menores.

2022-04-14 22:08 UTC, elagarrigue commented on app/src/main/java/ayds/lisboa/songinfo/home/model/entities/SpotifySong.kt
> +    val releaseDatePrecision: String
Definir un enumerado `DatePrecision` para evitar el acomplamiento de lógica del servidor en la vista

2022-04-14 22:08 UTC, elagarrigue commented on app/src/main/java/ayds/lisboa/songinfo/home/model/entities/SpotifySong.kt
> +    override val releaseDatePrecision: String= ""
El valor por default puede ser DATE

2022-04-14 22:08 UTC, elagarrigue commented on app/src/main/java/ayds/lisboa/songinfo/home/model/repository/external/spotify/tracks/SpotifyToSongResolver.kt
> +        return album[RELEASE_DATE_PRECISION].asString
Acá deben hacer el mapeo string -> enumerado

2022-04-14 22:08 UTC, elagarrigue commented on app/src/main/java/ayds/lisboa/songinfo/home/model/repository/local/spotify/sqldb/SpotifyLocalStorageImpl.kt
> +        db.execSQL("DROP TABLE IF EXISTS  $SONGS_TABLE")
Incorrecto, se está eliminando la db cada vez (a menos que se verifique la versión). No hace falta, reviertan a versión 1 y reinstalen la app.

2022-04-14 22:08 UTC, elagarrigue commented on app/src/main/java/ayds/lisboa/songinfo/home/model/repository/local/spotify/sqldb/SpotifyTableConstants.kt
> +            "$RELEASE_DATE_PRECISION_COLUMN string, " +
va a ser de tipo integer

2022-04-14 22:08 UTC, elagarrigue commented on app/src/main/java/ayds/lisboa/songinfo/home/model/repository/local/spotify/sqldb/SpotifyTableConstants.kt
> +            "$IMAGE_URL_COLUMN string" + ")"
revertir este cambio

2022-04-14 22:08 UTC, elagarrigue commented on app/src/main/java/ayds/lisboa/songinfo/home/view/DateResolver.kt
> +	private val months = arrayOf("January","February", "March","April", "May", "June","July","August","September","October","November","December")
no esta correctamente indentado

2022-04-14 22:08 UTC, elagarrigue commented on app/src/main/java/ayds/lisboa/songinfo/home/view/DateResolver.kt
> +            else -> ""
Acá se utilizará el enumerado

2022-04-14 22:08 UTC, elagarrigue commented on app/src/main/java/ayds/lisboa/songinfo/home/view/DateResolver.kt
> +
Un solo salto de línea entre funciones

2022-04-14 22:08 UTC, elagarrigue commented on app/src/main/java/ayds/lisboa/songinfo/home/view/HomeViewInjector.kt
> +    val songDescriptionHelper: SongDescriptionHelper = SongDescriptionHelperImpl(dateResolver)
indentación incorrecta

2022-04-14 22:08 UTC, elagarrigue commented on app/src/main/java/ayds/lisboa/songinfo/home/view/SongDescriptionHelperImpl.kt
> +
Revertir estos saltos de línea extra

2022-04-15 18:07 UTC, tadeo12 commented on app/src/main/java/ayds/lisboa/songinfo/home/model/entities/SpotifySong.kt
> +    override val releaseDatePrecision: String= ""
hola disculpa no entendemos, a que te referís con valor DATE?

2022-04-15 18:23 UTC, brancomartinezc commented on app/src/main/java/ayds/lisboa/songinfo/home/view/DateResolver.kt
> +	private val months = arrayOf("January","February", "March","April", "May", "June","July","August","September","October","November","December")
En el codigo local lo vemos con un solo tab, nos sabemos por que en github se ve con doble tab.

2022-04-15 20:54 UTC, elagarrigue commented on app/src/main/java/ayds/lisboa/songinfo/home/model/entities/SpotifySong.kt
> +    override val releaseDatePrecision: String= ""
`DatePrecision.DAY` en el caso de uds

2022-04-15 22:12 UTC, elagarrigue requested changes

2022-04-15 22:12 UTC, elagarrigue commented on app/src/main/java/ayds/lisboa/songinfo/home/model/repository/external/spotify/tracks/SpotifyToSongResolver.kt
> +        return DatePrecision.valueOf(precision)
Esto funciona ahora, pero podría cambiar. Si cambia el string "date" por ejemplo a "a_date", tendrían que cambiar el modelo en vez de esta clase. Mejor hacer un when y verificar explícitamente qué constante corresponde a qué valor del enumerado.
No se olviden de los principios SOLID cuando lo resuelvan.

2022-04-15 22:12 UTC, elagarrigue commented on app/src/main/java/ayds/lisboa/songinfo/home/view/DateResolver.kt
> +	private val months = arrayOf("January","February", "March","April", "May", "June","July","August","September","October","November","December")
Sí, es raro, ahora lo veo bien en la copia local

2022-04-17 11:59 UTC, elagarrigue requested changes
Últimos detalles

2022-04-17 11:59 UTC, elagarrigue commented on app/src/main/java/ayds/lisboa/songinfo/home/model/HomeModelInjector.kt
> +    val mapDatePrecision : MapDatePrecision = MapDatePrecisionImpl()
El nombre no es clean, es una forma verbal para una clase. Mejor `datePrecisionMapper`

2022-04-17 11:59 UTC, elagarrigue commented on app/src/main/java/ayds/lisboa/songinfo/home/model/repository/external/spotify/tracks/SpotifyToSongResolver.kt
> +        val mapDatePrecision = HomeModelInjector.mapDatePrecision
Evitar la dependecia al injector ya que se puede. Inyectarlo vía constructor
`internal class JsonToSongResolver(private val datePrecisionMapper: DatePrecisionMapper)`

2022-04-18 19:40 UTC, elagarrigue approved these changes
Ahí quedó 🙌🏽

2022-04-18 19:40 UTC, merged