Refactor Inicial de database y otherInfoWindow
elagarrigue/AyDS22-AK-Lisboa2 pull request #2
Opened 2022-04-26 21:48 UTC by brancomartinezc

2022-04-27 13:05 UTC, elagarrigue requested changes

2022-04-27 13:05 UTC, elagarrigue commented on app/src/main/java/ayds/lisboa/songinfo/moredetails/fulllogic/OtherInfoWindow.kt
> +        "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d4/Lastfm_logo.svg/320px-Lastfm_logo.svg.png"
contante mejor

2022-04-27 13:05 UTC, elagarrigue commented on app/src/main/java/ayds/lisboa/songinfo/moredetails/fulllogic/OtherInfoWindow.kt
> +            "[*]$artistInfo"
definir constante para el prefijo

2022-04-27 13:05 UTC, elagarrigue commented on app/src/main/java/ayds/lisboa/songinfo/moredetails/fulllogic/OtherInfoWindow.kt
> +        dataBase!!.getInfo(artistName!!)
evitar los  !! , usar late init var

2022-04-27 13:05 UTC, elagarrigue commented on app/src/main/java/ayds/lisboa/songinfo/moredetails/fulllogic/OtherInfoWindow.kt
> +        createLastFMAPI().getArtistInfo(artistName).execute()
DRY `createLastFMAPI()`

2022-04-27 13:05 UTC, elagarrigue commented on app/src/main/java/ayds/lisboa/songinfo/moredetails/fulllogic/OtherInfoWindow.kt
> +        findViewById<View>(R.id.openUrlButton).setOnClickListener {
niveles de abstracción

2022-04-27 13:05 UTC, elagarrigue commented on app/src/main/java/ayds/lisboa/songinfo/moredetails/fulllogic/OtherInfoWindow.kt
> +        getArtist(jobj)["url"].asString
definir constantes para las propiedades del json

2022-04-27 13:05 UTC, elagarrigue commented on app/src/main/java/ayds/lisboa/songinfo/moredetails/fulllogic/OtherInfoWindow.kt
> +            saveArtistInDataBase(artistInfo)
Side effect

2022-04-27 13:05 UTC, elagarrigue commented on app/src/main/java/ayds/lisboa/songinfo/moredetails/fulllogic/OtherInfoWindow.kt
> +            artistInfo = "No Results"
constante

2022-04-27 13:05 UTC, elagarrigue commented on app/src/main/java/ayds/lisboa/songinfo/moredetails/fulllogic/OtherInfoWindow.kt
> +        artistBiography!!.asString.replace("\\n", "\n")
evitar el !!

2022-04-27 16:35 UTC, JuanSanchez00 commented on app/src/main/java/ayds/lisboa/songinfo/moredetails/fulllogic/OtherInfoWindow.kt
> +        createLastFMAPI().getArtistInfo(artistName).execute()
Aca deberíamos agregar una propiedad lastFMAPI que luego se inicialice en un método?

2022-04-27 19:57 UTC, elagarrigue commented on app/src/main/java/ayds/lisboa/songinfo/moredetails/fulllogic/OtherInfoWindow.kt
> +        createLastFMAPI().getArtistInfo(artistName).execute()
correcto, como con la DB

2022-04-27 21:33 UTC, brancomartinezc commented
el commit "cambio de git add . por elvis operator en parametro de getArtistInfo" en realidad es "cambio de !! por elvis operator en parametro de getArtistInfo" (no se por que me quedo eso de git add . en el nombre)

2022-04-28 11:44 UTC, elagarrigue requested changes
Muy bien, un último detalle

2022-04-28 11:44 UTC, elagarrigue commented on app/src/main/java/ayds/lisboa/songinfo/moredetails/fulllogic/OtherInfoWindow.kt
> +        findViewById<View>(R.id.openUrlButton).setOnClickListener {
Definir una propiedad openUrlButton para no tener que hacer el findViewById, como con las otras views

2022-04-28 11:44 UTC, elagarrigue requested changes
Muy bien, un último detalle

2022-04-28 18:59 UTC, elagarrigue requested changes

2022-04-28 18:59 UTC, elagarrigue commented on app/src/main/java/ayds/lisboa/songinfo/moredetails/fulllogic/OtherInfoWindow.kt
> +        initOpenURLButton()
Se pueden unir los "initView" en uno sólo, comparten nivel de abstracción y es más fácil de encontrar donde agregar uno nuevo.

2022-04-28 18:59 UTC, elagarrigue commented on app/src/main/java/ayds/lisboa/songinfo/moredetails/fulllogic/OtherInfoWindow.kt
> +        getArtistInfo(intent.getStringExtra(ARTIST_NAME)?:"")
la obtención del parámetro es otro nivel de abstracción. Además, no hace falta pasarlo por parámetro, mejor que sea el primer paso de getArtistInfo (evitar parámetros es más clean)

2022-04-28 18:59 UTC, elagarrigue commented on app/src/main/java/ayds/lisboa/songinfo/moredetails/fulllogic/OtherInfoWindow.kt
> +    }
Esto es algo peligroso. Si hay una excepción se hace el catch, y luego se intenta acceder al late init, crash en ejecución. Mejor:
```suggestion
    private fun getArtistInfoFromService(): String {
        lateinit var queryArtistInfo: JsonObject
        lateinit var artistBiography: JsonElement
        return try {
            val queryArtistInfo = getQueryBodyOfArtistInfoFromService()
            val artistBiography = getArtistBiography(queryArtistInfo)
            setOnClickerListenerToOpenURLButton(queryArtistInfo)
            getStringArtistInfoFromService(artistBiography)
        } catch (e1: IOException) {
            e1.printStackTrace()
            ""
        }
    }
```

2022-04-29 13:36 UTC, elagarrigue requested changes
último detalle :)

2022-04-29 13:36 UTC, elagarrigue commented on app/src/main/java/ayds/lisboa/songinfo/moredetails/fulllogic/OtherInfoWindow.kt
> +        textPaneArtistBio = findViewById(R.id.textPane2)
Debería estar en `initViews`

2022-04-29 14:50 UTC, elagarrigue approved these changes
Ahí quedó

2022-04-29 14:50 UTC, merged